"""Agregar campo de visibilidad a servicios

Revision ID: 62d12d42393f
Revises: de4b32c01736
Create Date: 2026-01-16 13:37:00.528484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62d12d42393f'
down_revision = 'de4b32c01736'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visible_en_pantalla', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicio', schema=None) as batch_op:
        batch_op.drop_column('visible_en_pantalla')

    # ### end Alembic commands ###
