"""Agregar campo preferencial

Revision ID: 7e8d6737cbbb
Revises: cf5fa0c2c699
Create Date: 2025-12-19 17:40:32.084725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e8d6737cbbb'
down_revision = 'cf5fa0c2c699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_preferencial', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('es_preferencial')

    # ### end Alembic commands ###
