"""Restaurar registrado_por_id

Revision ID: a9ebf0b059d7
Revises: 62d12d42393f
Create Date: 2026-01-20 07:40:17.832427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9ebf0b059d7'
down_revision = '62d12d42393f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registrado_por_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'usuario', ['registrado_por_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('registrado_por_id')

    # ### end Alembic commands ###
