"""Creacion inicial de tablas

Revision ID: cf5fa0c2c699
Revises: 
Create Date: 2025-08-13 00:37:54.673005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf5fa0c2c699'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_modulo', sa.String(length=100), nullable=False),
    sa.Column('prefijo_ticket', sa.String(length=3), nullable=False),
    sa.Column('letra_actual', sa.String(length=1), nullable=False),
    sa.Column('numero_actual', sa.Integer(), nullable=True),
    sa.Column('color_hex', sa.String(length=7), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_modulo'),
    sa.UniqueConstraint('prefijo_ticket')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_funcionario', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('modulo_asignado', sa.String(length=100), nullable=True),
    sa.Column('numero_meson', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_funcionario')
    )
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_ticket', sa.String(length=10), nullable=False),
    sa.Column('rut_cliente', sa.String(length=15), nullable=False),
    sa.Column('modulo_solicitado', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('hora_registro', sa.DateTime(), nullable=False),
    sa.Column('hora_llamado', sa.DateTime(), nullable=True),
    sa.Column('hora_finalizado', sa.DateTime(), nullable=True),
    sa.Column('atendido_por_id', sa.Integer(), nullable=True),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('numero_meson', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atendido_por_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_ticket')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    op.drop_table('usuario')
    op.drop_table('servicio')
    # ### end Alembic commands ###
